FROM openjdk:18
EXPOSE 8080
ADD target/target/DevopsIntegrationApplication-0.0.1-SNAPSHOT.jar target/target/DevopsIntegrationApplication-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar","/app/DevopsIntegrationApplication-0.0.1-SNAPSHOT.jar"]
